using System;
using System.Linq;

namespace Improbable.Unreal.CodeGeneration.SchemaProcessing.Details
{
    public class UnrealPackageDetails
    {
        public readonly string NamespacePrefix;
        public readonly string Include;
        public readonly string SourceSchema;
        public readonly string CapitalisedCamelCase;

        // Indicates that we are within an autogenerated interop package from GDK.
        // We offer very little legacy SDK support for these packages as GDK does not use vast majority of the UnrealSDK API.
        // We use this flag to avoid generating relevant UClasses wherever possible in order to reduce build times.
        public readonly bool IsAutoGenerated;

        public UnrealPackageDetails(string canonicalName, string completePath, string package)
        {
            NamespacePrefix = string.Format("{0}::", package.Replace(".", "::"));
            Include = canonicalName.Replace(".schema", ".h");
            SourceSchema = completePath;
            var parts = package.Split(new[] { "." }, StringSplitOptions.RemoveEmptyEntries)
                               .Select<string, string>(s => char.ToUpperInvariant(s[0]) + s.Substring(1, s.Length - 1)).ToArray();
            CapitalisedCamelCase = string.Join(string.Empty, parts);
            IsAutoGenerated = package.Contains("improbable.unreal.generated");
        }
    }
}
