---
agent_transients: &agent_transients
  # This is designed to trap and retry failures because agent lost
  # connection. Agent exits with -1 in this case.
  exit_status: -1
  limit: 3

common: &common
  agents:
    - "agent_count=1"
    - "capable_of_building=gdk-for-unreal"
    - "environment=production"
    - "machine_type=double"  # cloud-agnostic SpatialOS node-size names
    - "platform=windows"
    - "permission_set=builder"
    - "scaler_version=2"
    - "queue=${CI_WINDOWS_BUILDER_QUEUE:-v3-1562267374-ab36457a07f081fe-------z}"
  retry:
    automatic:
      - <<: *agent_transients
  timeout_in_minutes: 60
  plugins:
    - git-clean#v0.0.1:
        flags: "-ffdx --exclude=UnrealEngine --exclude=UnrealEngine-Cache"
    - ca-johnson/taskkill#v4.1: ~

# NOTE: step labels turn into commit-status names like {org}/{repo}/{pipeline}/{step-label}, lower-case and hyphenated.
# These are then relied on to have stable names by other things, so once named, please beware renaming has consequences.

steps:
  - label: "build-GDK-:windows:"
    command: "powershell ./ci/setup-and-build-gdk.ps1 -target_platform Win64"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    artifact_paths:
      - "UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs/*"

  - label: "build-GDK-:linux:"
    command: "powershell ./ci/setup-and-build-gdk.ps1 -target_platform Linux"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    artifact_paths:
      - "UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs/*"
