@startuml Working sets - all on the same ServerWorker
entity ServerWorker
database Runtime
entity StrategyWorker


ServerWorker -> Runtime: Create Marker Entity

StrategyWorker -> Runtime: **E1** should migrate

Runtime -> ServerWorker: Active handover a member entity **E1**

ServerWorker -> ServerWorker: **AuthorityLost** on **E1**
note right 
    Unwanted
end note

ServerWorker -> Runtime: Send Active handover ACK

Runtime -> StrategyWorker: Deliver the active handover ACK

StrategyWorker -> Runtime: Assign **E1** to another worker

Runtime -> StrategyWorker: Marker Entity created

StrategyWorker -> Runtime: Migrate requested entities to the correct partition

Runtime -> ServerWorker: Soft handover logic

ServerWorker -> Runtime: Write soft handover ACKs

Runtime -> StrategyWorker: Deliver ACKs

group Writes to different entities - no ordering guarantees
    StrategyWorker -> Runtime: Write list of set members to the marker
    StrategyWorker -> Runtime: Write Marker Entity ID to set member 1
    StrategyWorker -> Runtime: Write Marker Entity ID to set member 2...
    StrategyWorker -> Runtime: Write Marker Entity ID to set member N
end

group Writes to different entities - no ordering guarantees
    ServerWorker <- Runtime: Write list of set members to the marker
    ServerWorker <- Runtime: Write Marker Entity ID to set member 1
    ServerWorker <- Runtime: Write Marker Entity ID to set member 2...
    ServerWorker <- Runtime: Write Marker Entity ID to set member N
end
@enduml
