@startuml Working sets - multiple ServerWorkers
entity RequestingServerWorker
entity InitiallyAuthServerWorker
database Runtime
entity StrategyWorker

InitiallyAuthServerWorker -> InitiallyAuthServerWorker: Store local information about a working set
InitiallyAuthServerWorker -> Runtime: Create Marker Entity

Runtime -> StrategyWorker: Marker Entity created

StrategyWorker -> Runtime: Migrate requested entities to the correct partition

Runtime -> RequestingServerWorker: Soft handover logic
Runtime -> InitiallyAuthServerWorker: Soft handover logic

RequestingServerWorker -> Runtime: Write soft handover ACKs
InitiallyAuthServerWorker -> Runtime: Write soft handover ACKs

Runtime -> StrategyWorker: Deliver ACKs

group Writes to different entities - no ordering guarantees
    group AuthorityDelegation
        StrategyWorker -> Runtime: Delegate set member 1 to correct partition
        StrategyWorker -> Runtime: Delegate set member 2... to correct partition
        StrategyWorker -> Runtime: Delegate set member N to correct partition
    end
    StrategyWorker -> Runtime: Write list of set members to the marker
    StrategyWorker -> Runtime: Write Marker Entity ID to set member 1
    StrategyWorker -> Runtime: Write Marker Entity ID to set member 2...
    StrategyWorker -> Runtime: Write Marker Entity ID to set member N
end

alt Set member 1 authority -> Marker Entity -> Remaining set members' authority -> Set member data updates
    Runtime -> RequestingServerWorker: You have auth over Member 1
    RequestingServerWorker -> RequestingServerWorker: <color:red>No local working set data available, call <b>AuthGain</b></color> 
    note right
        Unwanted
    end note
    Runtime -> RequestingServerWorker: Marker Entity defines a Working Set of Member 1..N
    RequestingServerWorker -> RequestingServerWorker: <color:red>Working set data available, call <b>AuthLost</b></color>
    note right
        Unwanted
    end note
    Runtime -> RequestingServerWorker: You have auth over Member 2..N-1
    RequestingServerWorker -> RequestingServerWorker: No AuthGain calls due to a working set not being formed
    Runtime -> RequestingServerWorker: You have auth over Member N
    RequestingServerWorker -> RequestingServerWorker: Working set formed, call <b>AuthGain</b>
else Set member data updates -> Set member 1 authority -> Marker Entity -> Remaining set members' authority
    Runtime -> RequestingServerWorker: You have auth over Member 1
    RequestingServerWorker -> RequestingServerWorker: Member 1 refers to an unknown Marker Entity, no <b>AuthGain</b>
    note right
        Requires some kind of ordering to ensure Members 1..N
        come into view with the state update applied
    end note
    Runtime -> RequestingServerWorker: Marker Entity defines a Working Set of Member 1..N
    RequestingServerWorker -> RequestingServerWorker: Working set data available
    Runtime -> RequestingServerWorker: You have auth over Member 2..N-1
    RequestingServerWorker -> RequestingServerWorker: No AuthGain calls due to a working set not being formed
    Runtime -> RequestingServerWorker: You have auth over Member N
    RequestingServerWorker -> RequestingServerWorker: Working set formed, call <b>AuthGain</b>
else Marker Entity -> Set members' authority -> Set member data updates
    Runtime -> RequestingServerWorker: Marker Entity defines a Working Set of Member 1..N
    Runtime -> RequestingServerWorker: You have auth over Member 1..N-1
    RequestingServerWorker -> RequestingServerWorker: No AuthGain calls due to a working set not being formed
    Runtime -> RequestingServerWorker: You have auth over Member N
    RequestingServerWorker -> RequestingServerWorker: Working set formed, call <b>AuthGain</b>
end
@enduml
