#!/usr/bin/env bash
set -euo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

# Only run purge script on Windows agents, as `premerge` runs on a Linux box
if [[ ${BUILDKITE_AGENT_META_DATA_OS} == "windows" ]]; then
    powershell -NoProfile -NonInteractive ci/purge.ps1 -projectRoot "$(pwd)/"
fi